# STATS.R is a stats file I made to get some rough results
# This who thing could be wrong, I have no idea, this is
# my first time doing these sorts of stats.
# I will explain each stat I am performing whereever they are in the file.

# I did graph some stats but graphing is truly not my strong suit so I didn't do it often

library(vegan)
library(cluster)
library(factoextra)
library(dplyr)
library(ggplot2)

# DATA
# loading the data generated by running MDS.R

# MDS_2D for daidones results
coords <- read.table("../data_output/MDS_2D.txt", header = TRUE)
# stimuli
stim_metadata <- read.csv("../data/stimuli.csv")
# combine the two
stim_metadata <- stim_metadata[match(rownames(coords), stim_metadata$FileName), ]


# participant coord
speaker_coords <- read.csv("../data/speaker_coords.csv", row.names = 1)

# participant metadata
speakers_meta <- read.csv("../data/speaker_metadata.csv")
colnames(speakers_meta) <- c("ID", "Age", "L1", "L2", "L_Studied", "L_Heard", "Musical", "Hearing", "Phonetics") # I am renaming these to better names

speakers_meta <- speakers_meta[match(rownames(speaker_coords), speakers_meta$ID), ]

raw_data <- read.csv("../data/speaker_data.csv")





# Stimuli based stats

# TEST 1
# tests if 'pVt' sounds and 'gVt' sounds form different clusters
set.seed(42)
context_test <- adonis2(coords ~ Context, data = stim_metadata, method = "euclidean")
print(context_test)




# TEST 2
# tests if Context and Condition (Palatalization) affect grouping as a whole
set.seed(42)
final_test <- adonis2(coords ~ Context * Condition, data = stim_metadata, method = "euclidean")
print(final_test)




# TEST 3
# tests specific breakdown of Context, Condition, and their Interaction
set.seed(42)
final_breakdown <- adonis2(coords ~ Context * Condition, data = stim_metadata, method = "euclidean", by = "terms")
print(final_breakdown)




# TEST 4
# find the optimal number of clusters (Silhouette Method)
set.seed(42)
clusters <- fviz_nbclust(coords, kmeans, method = "silhouette")
print(clusters$data)


# TEST 5
# K-Means clustering to check if the computer groups match Context (p vs g)
set.seed(42)
km_result <- kmeans(coords, centers = 2)
print(table(km_result$cluster, stim_metadata$Context))




# TEST 6
# test if one sound group (p vs g) is more "spread out" (dissimilar) than the other
set.seed(42)
dispersion <- betadisper(dist(coords), stim_metadata$Context)
print(anova(dispersion))








# Participant analysis :^)

# TEST 7
# tests if having a background in Phonetics changes the perceptual map
set.seed(42)
phonetics_test <- adonis2(speaker_coords ~ Phonetics, data = speakers_meta, method = "euclidean")
print(phonetics_test)




# TEST 8
# tests if being a Musician changes the perceptual map
set.seed(42)
speakers_meta$Is_Musician <- ifelse(speakers_meta$Musical == "No", "No", "Yes")
musicality_test <- adonis2(speaker_coords ~ Is_Musician, data = speakers_meta, method = "euclidean")
print(musicality_test)




# tEST 9
# Tests if being Bilingual vs Monolingual predicts position on Dimension 1
set.seed(42)
speakers_meta$Bilingual <- ifelse(speakers_meta$L2 == "No" | speakers_meta$L2 == "None", "Monolingual", "Bilingual")
d1_test <- lm(D1 ~ Bilingual, data = cbind(speaker_coords, speakers_meta))
print(summary(d1_test))



# TEST 9.5
set.seed(42)
bilingual_global_test <- adonis2(speaker_coords ~ Bilingual, data = speakers_meta, method = "euclidean")
print(bilingual_global_test)




# TEST 10
# tests if the number of languages studied correlates with Dimension 2
set.seed(42)
speakers_meta$Lang_Count <- sapply(strsplit(as.character(speakers_meta$L_Studied), ","), length)
speakers_meta$Lang_Count[speakers_meta$L_Studied == "No"] <- 0
lang_corr <- cor.test(speaker_coords$D2, speakers_meta$Lang_Count)
print(lang_corr)

# Test 10 does give a nice significant result but it is only significant because of one person
# who listed 20 languages. 




# TEST 11
# tests if Musicians are more consistent (tighter clusters) than Non-Musicians
set.seed(42)
disp_musician <- betadisper(dist(speaker_coords), speakers_meta$Is_Musician)
print(anova(disp_musician))




# TEST 12
# tests if the combination of Phonetics + Music background creates a unique effect
set.seed(42)
interaction_test <- adonis2(speaker_coords ~ Phonetics * Is_Musician, data = speakers_meta, method = "euclidean")
print(interaction_test)







# STRUCTURAL ANALYSIS (How the groups were made :)

group_stats <- raw_data %>%
  group_by(PARTICIPANT) %>%
  summarise(
    # Count non-empty groups
    Num_Groups = sum(GROUP != "" & tolower(GROUP) != "nan" & !is.na(GROUP)),
    # Calculate average size (approximate based on commas + 1)
    Avg_Group_Size = mean(stringr::str_count(GROUP, ",") + 1, na.rm = TRUE)
  )

speaker_coords$PARTICIPANT <- rownames(speaker_coords)

master_df <- merge(speakers_meta, speaker_coords, by.x = "ID", by.y = "PARTICIPANT")
master_df <- merge(master_df, group_stats, by.x = "ID", by.y = "PARTICIPANT")




# TEST 13
# D1 for people who made fewer big groups or more small groups
test_d1_groups <- cor.test(master_df$D1, master_df$Num_Groups)
print(test_d1_groups)

# I learned to graph this one lol
ggplot(master_df, aes(x = Num_Groups, y = D1)) +
  geom_point(size = 3, color = "purple") +
  geom_smooth(method = "lm", color = "black", se = FALSE) +
  theme_minimal() +
  labs(
    title = "Dimension 1 Represents Sorting Style",
    subtitle = "Fewer Groups (Lumpers) vs. Many Groups (Splitters)",
    x = "Number of Groups Made",
    y = "Dimension 1 Coordinate"
  )




# TEST 14:
# Testing linguistic enrichment for D2
test_d2_groups <- cor.test(master_df$D2, master_df$Num_Groups)
print(test_d2_groups)





# TEST 15:
# Seeing if the amount of languages studies matter - but we also are checking without one outlier who supposedly speaks 20
master_df$Lang_Count <- sapply(strsplit(as.character(master_df$L_Studied), ","), length)
master_df$Lang_Count[master_df$L_Studied == "No"] <- 0

polyglot <- subset(master_df, ID == "DC000017")
print(polyglot$Num_Groups, mean(master_df$Num_Groups))

# Doing the test without DC000017
df_clean <- subset(master_df, ID != "DC000017")
print(cor.test(df_clean$D2, df_clean$Lang_Count))


# TEST 16
# Testing if musical experience has an affect in D3 

# I also graphed this one :^)
ggplot(master_df, aes(x = Is_Musician, y = D3, fill = Is_Musician)) +
  geom_boxplot() +
  theme_minimal() +
  labs(title = "Dimension 3: Musicians vs Non-Musicians")

test_d3_music <- t.test(D3 ~ Is_Musician, data = master_df)
print(test_d3_music)



# TEST 17: 
# This test sort of brute forces dirfuign out all 5 dimensions but it upholds what we discussed before
# though it might help is discover anything about the 4th/5th dimension

dimensions <- c("D1", "D2", "D3", "D4", "D5")
variables <- c("Age", "Lang_Count", "Num_Groups", "Avg_Group_Size") 


# This is for continuous variables like how many languages a participant might know
for (dim in dimensions) {
  for (var in variables) {
    res <- cor.test(master_df[[dim]], master_df[[var]])
    
    if (res$p.value < 0.10) {
      cat(sprintf("  MATCH FOUND: %s vs %s -> r = %.2f (p = %.4f)\n", 
                  dim, var, res$estimate, res$p.value))
    }
  }
}


# This part is for yes/no vars like if they took a phonetics class
categories <- c("Is_Musician", "Phonetics", "Bilingual")

for (dim in dimensions) {
  for (cat_var in categories) {

    tryCatch({
      res <- t.test(master_df[[dim]] ~ master_df[[cat_var]])
      
      if (res$p.value < 0.10) {
        cat(sprintf("  MATCH FOUND: %s by %s -> p = %.4f\n", 
                    dim, cat_var, res$p.value))
      }
    }, error = function(e) {})
  }
}
