# STATS.R is a stats file I made to get some rough results
# This who thing could be wrong, I have no idea, this is
# my first time doing these sorts of stats.
# I will explain each stat I am performing whereever they are in the file.

library(vegan)
library(cluster)
library(factoextra)

# DATA
# loading the data generated by running MDS.R

# MDS_2D for daidones results
coords <- read.table("../data_output/MDS_2D.txt", header = TRUE)
# stimuli
stim_metadata <- read.csv("../data/stimuli.csv")
# combine the two
stim_metadata <- stim_metadata[match(rownames(coords), stim_metadata$FileName), ]


# participant coord
speaker_coords <- read.csv("../data/speaker_coords.csv", row.names = 1)

# participant metadata
speakers_meta <- read.csv("../data/speaker_metadata.csv")
colnames(speakers_meta) <- c("ID", "Age", "L1", "L2", "L_Studied", "L_Heard", "Musical", "Hearing", "Phonetics") # I am renaming these to better names

speakers_meta <- speakers_meta[match(rownames(speaker_coords), speakers_meta$ID), ]





# Stimuli based stats

# TEST 1
# tests if 'pVt' sounds and 'gVt' sounds form different clusters
set.seed(42)
context_test <- adonis2(coords ~ Context, data = stim_metadata, method = "euclidean")
print(context_test)




# TEST 2
# tests if Context and Condition (Palatalization) affect grouping as a whole
set.seed(42)
final_test <- adonis2(coords ~ Context * Condition, data = stim_metadata, method = "euclidean")
print(final_test)




# TEST 3
# tests specific breakdown of Context, Condition, and their Interaction
set.seed(42)
final_breakdown <- adonis2(coords ~ Context * Condition, data = stim_metadata, method = "euclidean", by = "terms")
print(final_breakdown)




# TEST 4
# find the optimal number of clusters (Silhouette Method)
set.seed(42)
fviz_nbclust(coords, kmeans, method = "silhouette")




# TEST 5
# K-Means clustering to check if the computer groups match Context (p vs g)
set.seed(42)
km_result <- kmeans(coords, centers = 2)
print(table(km_result$cluster, stim_metadata$Context))




# TEST 6
# test if one sound group (p vs g) is more "spread out" (dissimilar) than the other
set.seed(42)
dispersion <- betadisper(dist(coords), stim_metadata$Context)
print(anova(dispersion))








# Participant analysis :^)

# TEST 7
# tests if having a background in Phonetics changes the perceptual map
set.seed(42)
phonetics_test <- adonis2(speaker_coords ~ Phonetics, data = speakers_meta, method = "euclidean")
print(phonetics_test)




# TEST 8
# tests if being a Musician changes the perceptual map
set.seed(42)
speakers_meta$Is_Musician <- ifelse(speakers_meta$Musical == "No", "No", "Yes")
musicality_test <- adonis2(speaker_coords ~ Is_Musician, data = speakers_meta, method = "euclidean")
print(musicality_test)




# tEST 9
# Tests if being Bilingual vs Monolingual predicts position on Dimension 1
set.seed(42)
speakers_meta$Bilingual <- ifelse(speakers_meta$L2 == "No" | speakers_meta$L2 == "None", "Monolingual", "Bilingual")
d1_test <- lm(D1 ~ Bilingual, data = cbind(speaker_coords, speakers_meta))
print(summary(d1_test))




# TEST 10
# tests if the number of languages studied correlates with Dimension 2
set.seed(42)
speakers_meta$Lang_Count <- sapply(strsplit(as.character(speakers_meta$L_Studied), ","), length)
speakers_meta$Lang_Count[speakers_meta$L_Studied == "No"] <- 0
lang_corr <- cor.test(speaker_coords$D2, speakers_meta$Lang_Count)
print(lang_corr)




# TEST 11
# tests if Musicians are more consistent (tighter clusters) than Non-Musicians
set.seed(42)
disp_musician <- betadisper(dist(speaker_coords), speakers_meta$Is_Musician)
print(anova(disp_musician))




# TEST 12
# tests if the combination of Phonetics + Music background creates a unique effect
set.seed(42)
interaction_test <- adonis2(speaker_coords ~ Phonetics * Is_Musician, data = speakers_meta, method = "euclidean")
print(interaction_test)